sudo: required
language: c
env: 
  global: 
  - secure: FTAcwV1i+7U7+ibyKY2+ijLtUR8bx8T2LEykah51GEaQNdKZSX6FysqWMHvHGZfMjuMa3yCI1ViYfovro1kJzkUlbBExZJrcMPsCkbu8qIsmXXBl4dl+pXxo6K+QxoAUxMIpaEfLE3c9/grT8E6FigKDMxc3U0y1bSWOh+izIGF1TcKl929mvlX4Hnja3wFuVdrRRysmBX47tpVjGHglsj2WSB4G/UZPrdpOndAiQVh+eZUyHA9jBIXQ8PkVsMfWzxHMDYWyWRuj83m72fleFCzRShW5be25ybKk1wVd30/xVD6fOo6HvMAgxuGQNeEullJYTcWMtDRyDUCy5ZUseRbC5HKSctiCWn1sAZLTtc6ARYqa1yNVIw13E5hhZfYmfnQuGLCElVcrpa4lKQBOAHsDiEo77V14LFFrxShltYOfFk4bdpCYS8+FNiIszq4Q9wowOecU6SPsn0frKCcu4EpBi0e2vBpyV9W8I8abYEk5oyNkOG0am6xWiONFQjGN2An3i3aa+8EdsQj3AXX3FbupItMJFWyGrqSbeLgHJn5wFrjuWY2NhkREQPqAkwjtubCMhmV8T3zrWsUxZsNRAf4yPMhRC30Hdpyu+ZKXybWIWgOxM7Epyy0g/xKEzveG8DTIbHoVV6521UNc/hQvzdKVtqqHdjulFnsBTTsqVHY=
  - secure: on3TbHXq5cl67el4yRGqE2HMskOoJJnxbmDN+OpKFrKqhEksyN3oFahSo12fOSOCjUGidMsHIt4YqVwnczlZu4Al0NfQP81nvl3a9cRTLF3GxpOocDyurb5obgx6eTHEHO/s+JI/lwXrun/PPzdvO41FgkkhZAKkvrKqfdwr7PXniFK0nmkByWSlHr45Chi41bxed9sDk5GOc2rCFrvG5WqUPNJ4dcc2lucXUVsTrGfZPhKm5Em2e72gWsL3/j2AUnswoXNwJ8rZ9ZZDKMqWncPvWMWSAyI9p6wPa3zO0aDh/NJApTiKpGdB2pqlXRmJqDHr102ldkZ+kwcK22ajXWpbd09qoHw4HIuN5O5vDHNN/n7MbC660l8hfdMkiFUX+P47AQLGhe3XxzALg0w0H4h4xVrdSzp7jZjS/XjuG9l/nJPHF7CtFMjKUaXzZEoxe8OqEAPfJyMrjiC2O+p+9E3QTP6U4F8mAglQTOxLtbk4HhzWUkj1G65IBhXpYtl7gHkr6wdnwH2cs5CIsgUeRoSF6C1QTVdY321qVyoFBMRO/mX4mipuiwAD6DFltbCnwAKcT34EUodTRhIGIOseasy/SatFIGtNdxKIiCVtaIqaZuuVUqdKSaCSL8o5dW+2HqFdMOU3HOLEGvilYNzR2ulxYzIqqnpT8fwTiPCbtHQ=
install: 
- sudo apt-get update -qq
- sudo apt-get install -y make python-setuptools python-pip python-virtualenv python-dev
- sudo apt-get install -y g++ cmake libboost1.55-all-dev libcurl4-openssl-dev
- sudo apt-get install -y zlib1g-dev libbz2-dev flex bison autoconf
script: 
- wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-14.04-amd64.tar.gz
- tar xf dx-toolkit-current-ubuntu-14.04-amd64.tar.gz
- source dx-toolkit/environment
- make -C dx-toolkit/share/dnanexus/src/cpp/
- wget https://github.com/samtools/htslib/releases/download/1.3.1/htslib-1.3.1.tar.bz2
- tar xf htslib-1.3.1.tar.bz2
- export HTSLIB_ROOT=$(pwd)/htslib-1.3.1
- sed -e '/capacity > 32768/ s/^/\/\//' -i htslib-1.3.1/hfile.c
- make
- cd htslib-1.3.1 && ./configure --enable-plugins --enable-libcurl && make && sudo make install && cd ..
- sudo cp hfile_dnanexus.so /usr/local/libexec/htslib
- wget https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
- tar xf samtools-1.3.1.tar.bz2
- cd samtools-1.3.1 && ./configure --with-htslib=system --without-curses && make && sudo make install && cd ..
- export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
- bash tests/test.sh
dist: trusty
