sudo: required
dist: trusty
language: c

install:
    sudo apt-get update -qq
    sudo apt-get install -y make python-setuptools python-pip python-virtualenv python-dev \
      g++ cmake libboost1.55-all-dev libcurl4-openssl-dev zlib1g-dev libbz2-dev flex bison \
      autoconf

script:
    # Install dx-toolkit
    wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-14.04-amd64.tar.gz
    tar xf dx-toolkit-current-ubuntu-14.04-amd64.tar.gz
    source dx-toolkit/environment
    # Build dxcpp
    make -C dx-toolkit/share/dnanexus/src/cpp/
    # Download and build htslib
    wget https://github.com/samtools/htslib/releases/download/1.3.1/htslib-1.3.1.tar.bz2
    tar xf htslib-1.3.1.tar.bz2
    export HTSLIB_ROOT=$(pwd)/htslib-1.3.1
    # Remove line that caps capacity at 32kb, otherwise there will be lots of
    # small requests
    sed -e '/capacity > 32768/ s/^/\/\//' -i htslib-1.3.1/hfile.c
    make
    cd htslib-1.3.1 && ./configure --enable-plugins --enable-libcurl && make && sudo make install && cd ..
    # Copy the dnanexus plugin to the plugin directory
    sudo cp hfile_dnanexus.so /usr/local/libexec/htslib
    # Install samtools using the existing htslib build
    wget https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
    tar xf samtools-1.3.1.tar.bz2
    cd samtools-1.3.1 && ./configure --with-htslib=system --without-curses && make && sudo make install && cd ..
    export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
