sudo: required
dist: trusty
language: c

install:
    - sudo apt-get update -qq
    - sudo apt-get install -y make python-setuptools python-pip python-virtualenv python-dev
    - sudo apt-get install -y g++ cmake libboost1.55-all-dev libcurl4-openssl-dev
    - sudo apt-get install -y zlib1g-dev libbz2-dev flex bison autoconf

script:
    # Install dx-toolkit
    - wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-14.04-amd64.tar.gz
    - tar xf dx-toolkit-current-ubuntu-14.04-amd64.tar.gz
    - source dx-toolkit/environment
    # Build dxcpp
    - make -C dx-toolkit/share/dnanexus/src/cpp/
    # Download and build htslib
    - wget https://github.com/samtools/htslib/releases/download/1.3.1/htslib-1.3.1.tar.bz2
    - tar xf htslib-1.3.1.tar.bz2
    - export HTSLIB_ROOT=$(pwd)/htslib-1.3.1
    # Remove line that caps capacity at 32kb, otherwise there will be lots of
    # small requests
    - sed -e '/capacity > 32768/ s/^/\/\//' -i htslib-1.3.1/hfile.c
    - make
    - cd htslib-1.3.1 && ./configure --enable-plugins --enable-libcurl && make && sudo make install && cd ..
    # Copy the dnanexus plugin to the plugin directory
    - sudo cp hfile_dnanexus.so /usr/local/libexec/htslib
    # Install samtools using the existing htslib build
    - wget https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
    - tar xf samtools-1.3.1.tar.bz2
    - cd samtools-1.3.1 && ./configure --with-htslib=system --without-curses && make && sudo make install && cd ..
    - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
    - bash tests/test.sh
env:
  global:
    - secure: "jLalAEMYV6aIbyTDaSAQkLAK+Fx5REzHCEo6bMPf3VFzUjpwGyEyH2dUBZlGUhkyClzyKxgMOZi5zBCqhGWj8j3laQraBK9Bg6bTz/QlVFQvdrwSHYntSFDv/NXkzmrmThSa4zB9cQiceOlDNqmn2Knk/fNPvbps5pFnocJAK9Bd9yPVurC0v+2yXUj2J1+vpF+yU4S/SI14dobE0C78D8tne4Uq/hU0kPIzf/wcUxp7pcb9Y966BymLw15l1/4pd+DAwFGhMLNexMv6IeUmd6wiY7AtEfNaEN8SzXnJIcnqXBJwt5n3pw/STO5N9a86q+8Fw8WazwE9+273iN3NjJqOh3FRPpVoPfS7AoSRv/xCav6G6O7F1jeHI1KwkwCtqULNZNPubrHAp3EJfgsWTE+rqEzuJTxdJwFrIVXckkFMXQLBur1LrzK/bVNj9E7/AoZJ9vMW7NHJVOdu/wppCmKhFrl0owyuVQUC+zKvkTfSJhHTIA4XewT9mt2+0r6l5xPOP3wSVPPs7sRj8FkpvqVev9dWhzpEc23mwrZDdXlWgvHFVxGajoYlY7u84kzuVeZn078lf6+t5eU6QvdtGS9xQaAqXwaahj9MLUDEkJl1baqisfO7QWBoRiMcTt1rS0gspTYYfQtBUKahse3w2+v7c7a0at6yFVks9UTcb4Y="
    - secure: "n/CsSlwnu9qIz6BcnXUaVrDzWAitWmmQsn99IoUZlKM9ZEYiXzPsu/dq9DQC1iNe/pBFT4dJRXOR7CEggYDZpL7us0X8RSDDBCjxGviGUogHnzookM51FTlSbzozNWdh+HZP0KF9hR/t8S1F66app8XKumHZ4QKIh0zXW1m2woS/TCFS8yXBO7v0BUgNcJgyf6Y4xZ1pC0ZBIdhdClyIiZxNEKiuoHAuG90Kz2kNv4GsOQPe/5v7Ccl3yHIkVhsvYGII5xVw7tlaHeoFda2kxUP1T+W5vXIjBH0jb2UKq5xOU5K1A4zUArUlEPljpye4ntDZH0bRqcTuXBjsafKofCg08v0gIpWLWvAuMhHma8E1e2z+rmrB2LNORwtCEHM85HF5R40gy3yMG12nxCGoI/G5q6oVYSALiyS58jDChVSUOMcF5wVJFuGm+Sw0/vwOzWCZxEt9BZak3CsdOYB/pnIc+zUhJjG+VLqD7/SsoyxS+MfxuL4aYWyihbYpxycRSDqxIY7WBsavT5o22LXjayVLDMemxRFt1MOS780kSUgHVW+N+fKZtgxvtv/z6+x/Wk7Qx7HRyTcQXsSA1mFZbsrI3phGQoNK1OfFZcs7e9TN82LgVIoh1+JLvEaObghDfIiP9imnprgBwh/fCrgbOQDMLsyU040FkLZpu/9ny2U=" 
