script: 
- wget https://wiki.dnanexus.com/images/files/dx-toolkit-current-ubuntu-14.04-amd64.tar.gz
- tar xf dx-toolkit-current-ubuntu-14.04-amd64.tar.gz
- source dx-toolkit/environment
- make -C dx-toolkit/share/dnanexus/src/cpp/
- wget https://github.com/samtools/htslib/releases/download/1.3.1/htslib-1.3.1.tar.bz2
- tar xf htslib-1.3.1.tar.bz2
- export HTSLIB_ROOT=$(pwd)/htslib-1.3.1
- sed -e '/capacity > 32768/ s/^/\/\//' -i htslib-1.3.1/hfile.c
- make
- cd htslib-1.3.1 && ./configure --enable-plugins --enable-libcurl && make && sudo make install && cd ..
- sudo cp hfile_dnanexus.so /usr/local/libexec/htslib
- wget https://github.com/samtools/samtools/releases/download/1.3.1/samtools-1.3.1.tar.bz2
- tar xf samtools-1.3.1.tar.bz2
- cd samtools-1.3.1 && ./configure --with-htslib=system --without-curses && make && sudo make install && cd ..
- export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
- env
- dx ls
- bash tests/test.sh
sudo: required
dist: trusty
env: 
  global: 
  - secure: on3TbHXq5cl67el4yRGqE2HMskOoJJnxbmDN+OpKFrKqhEksyN3oFahSo12fOSOCjUGidMsHIt4YqVwnczlZu4Al0NfQP81nvl3a9cRTLF3GxpOocDyurb5obgx6eTHEHO/s+JI/lwXrun/PPzdvO41FgkkhZAKkvrKqfdwr7PXniFK0nmkByWSlHr45Chi41bxed9sDk5GOc2rCFrvG5WqUPNJ4dcc2lucXUVsTrGfZPhKm5Em2e72gWsL3/j2AUnswoXNwJ8rZ9ZZDKMqWncPvWMWSAyI9p6wPa3zO0aDh/NJApTiKpGdB2pqlXRmJqDHr102ldkZ+kwcK22ajXWpbd09qoHw4HIuN5O5vDHNN/n7MbC660l8hfdMkiFUX+P47AQLGhe3XxzALg0w0H4h4xVrdSzp7jZjS/XjuG9l/nJPHF7CtFMjKUaXzZEoxe8OqEAPfJyMrjiC2O+p+9E3QTP6U4F8mAglQTOxLtbk4HhzWUkj1G65IBhXpYtl7gHkr6wdnwH2cs5CIsgUeRoSF6C1QTVdY321qVyoFBMRO/mX4mipuiwAD6DFltbCnwAKcT34EUodTRhIGIOseasy/SatFIGtNdxKIiCVtaIqaZuuVUqdKSaCSL8o5dW+2HqFdMOU3HOLEGvilYNzR2ulxYzIqqnpT8fwTiPCbtHQ=
  - secure: guzXFIRvBoft41GUXC+s5lch2YgRNuczQZh82axTALfAr2kCnpDC5OYrsg/NDOw3HLrjbBKUElApKFUINbwKbLixHe5MWmpq1+VUcK8c9d8jYDmjZtZA/gDVUt435ShpAcGklsH3QGIYLN8QCVe7ynRyDpqreJeLO0MY1Y7AyhOl2lYm2ZB/aqs8y1qgPoY/VGgUrWUP5PzWSulX9R4bEaWio35Zvt+giXk1WCrc7k0hqBfy12WooJED5N5/ftuRBfxqRRVZbFkabuUfq1guFKjgA4x5BMLaL9PQ3fgGSxFvk+dVUspHha6JXdGf8485TM6NzoLEypVnpKJgV2pygVNuss/8uYyT3Tuwr6DkgU89ltfzGOLt9w4gSpIHV94ua/AhQ0llzSi7IGl6bUQT+xIW/dlQ7hj+43ls/woGQYYuKuubfe/QrCBz4uUYweVtO7g8qO9WpCui+k4mOKklPbSdfeFE2LnYYAp7WwsND+d2pPPl4Tie2tf6XF38FSWyhwtT82zCM9KlP/60/1agNE63IUFHYDSlHocFCS3dDHKQyPYRyol6A7q7YTDC1q4hz/NFkWmw8kGHKE3XmLXswdqMGlrnm6efDQApbERiYL7MCPdHyHuZzRdSdwxFIh6ylwPIavpWqRxR23cLvyXK9T6xd6B321E0TANEM8Znvjk=
install: 
- sudo apt-get update -qq
- sudo apt-get install -y make python-setuptools python-pip python-virtualenv python-dev
- sudo apt-get install -y g++ cmake libboost1.55-all-dev libcurl4-openssl-dev
- sudo apt-get install -y zlib1g-dev libbz2-dev flex bison autoconf
language: c
